ocaml-ppx/ppx_deriving

src_plugins/ppx_deriving_eq.ml, src_plugins/ppx_deriving_ord.ml, src_test/test_deriving_eq.ml, src_test/test_deriving_ord.ml
- Add tests for mutual recursive type to  src_test/test_deriving_eq.ml,
src_test/test_deriving_ord.ml
- Fix code generation for list type in eq and ord plugin to avoid the
error of 'let rec' restriction (This kind of expression is not
allowed as right-hand side of `let rec')
=> Fix error using when eq/ord with mutual-rec type

src/ppx_deriving.ml, src/ppx_deriving.mli, src_plugins/ppx_deriving_eq.ml, src_plugins/ppx_deriving_ord.ml, src_plugins/ppx_deriving_show.ml, src_test/test_deriving_eq.ml, src_test/test_deriving_ord.ml, src_test/test_deriving_show.ml
Related to whitequark/ppx_deriving#23
It works by adding a type signature to every generated function for both of these derivers, with strong polymorphic constraint.
=> Allow derivation of ord and show for mutually recursive types with polymorphic variable

README.md, src_plugins/ppx_deriving_ord.ml
Currently the generated code for ord looks like that:
~~~~{ocaml}
type v =
| Foo
| Bar of int* string
| Baz of string
[@@deriving ord]
let rec compare_v : v -> v -> int=
fun lhs  ->
fun rhs  ->
match (lhs, rhs) with
| (Foo ,Foo ) -> 0
| (Bar (lhs0,lhs1),Bar (rhs0,rhs1)) ->
(match (fun (a : int)  -> fun b  -> Pervasives.compare a b) lhs0
rhs0
with
| (-1)|1 as x -> x
| _ ->
(match (fun (a : string)  -> fun b  -> Pervasives.compare a b)
lhs1 rhs1
with
| (-1)|1 as x -> x
| _ -> 0))
| (Baz lhs0,Baz rhs0) ->
(match (fun (a : string)  -> fun b  -> Pervasives.compare a b) lhs0
rhs0
with
| (-1)|1 as x -> x
| _ -> 0)
| _ ->
let to_int = function | Foo  -> 0 | Bar (_,_) -> 1 | Baz _ -> 2 in
((fun (a : int)  -> fun b  -> Pervasives.compare a b)) (to_int lhs)
(to_int rhs)
~~~~
With this patch, it …
=> Simplifying generated code for ord

src/ppx_deriving.ml, src/ppx_deriving.mli, src_plugins/ppx_deriving_eq.ml, src_plugins/ppx_deriving_ord.ml, src_plugins/ppx_deriving_show.ml, src_test/test_deriving_eq.ml, src_test/test_deriving_ord.ml, src_test/test_deriving_show.ml
Shadowing standard type, while definitely bad style, will result in invalid generated code using ppx_deriving (and I know a code base with those...):
~~~~{ocaml}
type es =
| ESBool of bool
| ESString of string
and bool =
| Bfoo of int * ((int -> int) [@compare fun _ _ -> 0])
and string =
| Sfoo of String.t * ((int -> int) [@compare fun _ _ -> 0])
[@@deriving ord{ allow_std_type_masking }]
~~~~
will call `Pervasives.compare` for `ESBool` and `ESString`, yielding to a crash at runtime. The first solution implemented in this patch is to reject derivation of shadowed types. If you known what you're doing, you can use the `allow_std_type_masking` to force derivation (if possible), and try to call the good functions while generating code for the mutually recursive types (like the one added in …
=> Adding handling of shadowed standard types in mutually recursive types.

Makefile, pkg/topkg.ml
This pull request update topkg with the latest one, which include a patch to detect the '.lib' extension generated under windows with Ocaml + msvc.
It also add an install command to the makefile to be able to install the ppx without Opam on windows and linux, related to whitequark/ppx_deriving#16
=> Adding installation without Opam

src/ppx_deriving.ml, src/ppx_deriving.mli, src_plugins/ppx_deriving_ord.ml, src_test/test_deriving_ord.ml
Warning 4 is triggered by the code produced with the ppx_deriving_ord plugin (which uses wildcards). The warning does not make much sense in that case (because the code is auto generated), hence it can be safely deactivated in the `match` construct built by `ord`.
=> Remove warning 4

src_plugins/ppx_deriving_create.ml, src_plugins/ppx_deriving_eq.ml, src_plugins/ppx_deriving_ord.ml, src_plugins/ppx_deriving_show.ml
First attempt at fixing #39. Strategy: for every record field `{label : ty}`, put attributes of `label` into `ty`.
=> merge attributes of record fields and types (for OCaml 4.02.2)

Makefile
Flags to rm must come first on OSX. For example:
```
rm _build -rf
rm: _build: is a directory
rm: -rf: No such file or directory
```
=> Fix rm -rf in test, examples targets on OSX

src/ppx_deriving.ml
This is a necessary addition to apply something like #23 to
ppx_deriving_yojson.
Signed-off-by: Christoph Höger <christoph.hoeger@tu-berlin.de>
=> Handle polymorphic variants in free var calculation

src_plugins/ppx_deriving_eq.ml, src_test/test_deriving_eq.ml
This is necessary in case of recursive groups, due to
the let-rec restriction to syntactic functions.
Such a change is possibly necessary for other plugins
as well.
Signed-off-by: Christoph Höger <christoph.hoeger@tu-berlin.de>
=> Eta expand equality functions

_tags
The ppx\_deriving binary should be linked with `-linkall` so that plugins are free to use modules of the stdlib that are not referenced by ppx_deriving itself.
=> Link ppx_deriving_main with linkall

src/ppx_deriving.ml
This may yield an error in the concrete syntax, when the
modified AST is later dumped (e.g. for debugging purposes).
It might also fail later on (in case the compiler acts less
generous in that area).
Signed-off-by: Christoph Höger <christoph.hoeger@tu-berlin.de>
=> Do not create empty let-binding

pkg/META.in
=> Missing pkg/META.in description for `ppx_deriving.make`.

src/ppx_deriving.ml, src/ppx_deriving.mli
Easily read list valued attributes. E.g `[@aliases ["foo"; "bar"]]`
=> Add Ppx_deriving.Arg.list

src_plugins/ppx_deriving_show.ml, src_test/test_deriving_show.ml
This patch makes ppx_deriving_show honor [@printer] annotations
on the cases of a variant type, closing
https://github.com/whitequark/ppx_deriving/issues/77.
In particular, consider the following code:
type t =
| First [@printer fun fmt _ -> Format.fprintf fmt "first case"]
| Second
[@@deriving show]
let () =
Format.printf "%a, %a@." pp First pp Second
It now outputs "first case, Printer_variant.Second".
=> Honor the [@printer] annotation for variant types.

src_plugins/ppx_deriving_map.cppo.ml, src_test/test_deriving_map.cppo.ml
Examples such as
```
type 'a t = { x : 'a; y : string } [@@deriving map]
type 'a t = A of 'a | B of string [@@deriving map]
```
lead to a type error on the non-polymorphic field/constructor arg.  Is this the expected behaviour?  
This patch copies such fields/args instead.
=> Fix deriving.map on records with non-poly field

src/ppx_deriving.cppo.ml, src/ppx_deriving.mli, src_plugins/ppx_deriving_iter.cppo.ml, src_plugins/ppx_deriving_map.cppo.ml, src_test/test_deriving_iter.cppo.ml, src_test/test_deriving_map.cppo.ml
The signature generated for `map` was less general than the actual
implementation ie
```
type 'a t = ...
val map : ('a -> 'a) -> 'a t -> 'a t
```
as opposed to
```
val map : ('a -> 'b) -> 'a t -> 'b t
```
A bit of new machinary is added to ppx_deriving.ml to support this
`core_type_with_fresh_vars`.
For `iter` the signature was actually more general than the
implementation
```
type ('a,'b) t = ...
val iter : ('a -> unit) -> ('b -> unit) -> ('a,'b) t -> unit
```
whereas the implementation gave
```
val iter : ('a -> unit) -> ('a -> unit) -> ('a,'a) t -> unit
```
This was due to a type constraint on the `Ptyp_var` that forced
all the poly arg functions to the same type.
=> Fix type problems in 'map' and 'iter'.

_tags, src/ppx_deriving.cppo.ml, src/ppx_deriving.mli
Previously it would use a polymorphic variant version of result. This is
no longer necessary as OCaml now has a standard result type.
The sanitize change will come in a different PR
Fix #75
=> Change Arg api to use Result.result

src/ppx_deriving.cppo.ml, src/ppx_deriving.mli
Sanitize can wrap an expression using a provided module name. If a
module name isn't provided, `Ppx_deriving_runtime` will be used as the
default.
@Drup can you verify the loc handling?
=> Parameterize sanitize over a module

README.md
Links to the sources of the `eq` and `show` plugins were broken because of a missing `cppo` extension.
=> Fix links to eq and show sources in the readme

src_plugins/ppx_deriving_eq.cppo.ml
I'm currently trying to use ppx_deriving in a codebase that uses some
GADTs, and running into the problem that the generated code does not
type-check. One extra difficulty is that the locations in the
generated code are wrong. For example, consider
type _ expr =
| Int : int -> int expr
| Prod : 'a expr * 'b expr -> ('a * 'b) expr
[@@deriving eq]
the current implementation will report
type _ expr =
^^^^^^^^^^^^^
File "foo.ml", line 1, characters 0-98:
Error: This pattern matches values of type (ex#0 * ex#1) expr
but a pattern was expected which matches values of type int expr
Type ex#0 * ex#1 is not compatible with type int
after the present commit, one gets instead
| Prod : 'a expr * 'b expr -> ('a * 'b) expr
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "foo.ml", line 3, characters …
=> minor: per-constructor, per-field location in equality code

src/ppx_deriving.cppo.ml
Example:
type (_, 'a, 'b) split_list =
| Foo of unit
[@@deriving eq]
Before this commit:
let rec (equal_split_list :
'a 'b 'a 'b 'a 'b .
('a -> 'a -> Ppx_deriving_runtime.bool) ->
('b -> 'b -> Ppx_deriving_runtime.bool) ->
(_,'a,'b) split_list ->
(_,'a,'b) split_list -> Ppx_deriving_runtime.bool)
= ...
After this commit:
let rec (equal_split_list :
'a 'b .
('a -> 'a -> Ppx_deriving_runtime.bool) ->
('b -> 'b -> Ppx_deriving_runtime.bool) ->
(_,'a,'b) split_list ->
(_,'a,'b) split_list -> Ppx_deriving_runtime.bool)
= ...
=> Really remove duplicate in free type variables.

src/ppx_deriving.cppo.ml, src/ppx_deriving.mli
I could use an extension of the deriving interface to allow deriving definitions from module types.  The derived definitions would typically be a structure of the given signature or a functor producing or depending on it, though it could be regular functions involving first-class modules of the signature.  My current use-case is to generate the RPC client and server parts for a Thrift service.
=> Support deriving from module type declarations.

_tags, opam, src/ppx_deriving_main.cppo.ml
This patch add support for loading packages instead of just files. This makes the use of libraries inside ppx\_deriving plugins a lot easier.
To load a package, one must pass `package:package-name` to ppx\_deriving. The package must also use the `plugin` variable (or the deprecated `archive(plugin)` which is generated by oasis).
In the end the META of a ppx\_deriving plugin that is using this feature must look like:
```
package "show" (
version = "%{version}%"
description = "[@@deriving show]"
requires(-ppx_driver) = "ppx_deriving"
ppxopt(-ppx_driver) = "ppx_deriving,package:ppx_deriving.show"
requires(ppx_driver) = "ppx_deriving.api"
archive(ppx_driver, byte) = "ppx_deriving_show.cma"
archive(ppx_driver, native) = "ppx_deriving_show.cmxa"
plugin(ppx_driver, byte) = …
```
=> Add support for loading findlib packages instead of just files

src/ppx_deriving.cppo.ml, src/ppx_deriving.mli, src_plugins/ppx_deriving_create.cppo.ml, src_plugins/ppx_deriving_eq.cppo.ml, src_plugins/ppx_deriving_fold.cppo.ml, src_plugins/ppx_deriving_iter.cppo.ml, src_plugins/ppx_deriving_make.cppo.ml, src_plugins/ppx_deriving_map.cppo.ml, src_plugins/ppx_deriving_ord.cppo.ml, src_plugins/ppx_deriving_show.cppo.ml, src_test/test_deriving_eq.cppo.ml, src_test/test_deriving_fold.cppo.ml, src_test/test_deriving_iter.cppo.ml, src_test/test_deriving_ord.cppo.ml, src_test/test_deriving_show.cppo.ml
This removes the leading `Pervasives` module when matching on built-in types. It solves issues with ppx_import on 4.03 (where types are fully qualified).
=> Remove pervasives when appropriate.

src_plugins/ppx_deriving_show.cppo.ml, src_test/test_deriving_show.cppo.ml
=> Fixed [%printer] handling to include multi-arg variant constructors

src_plugins/ppx_deriving_map.cppo.ml, src_test/test_deriving_map.cppo.ml
...and type sigs as per #83.
changes `expr_of_typ` to receive a type_declaration and hides it
behind an option type (note; possibly better to provide a `core_type
option` instead).
from within the deriver structure, using `expr_of_typ` to generate code
for inherited polymorphic variants will raise an error.  I don't know
if this is actually done anywhere.
=> Fix for issue with inherited polymorphic variants

pkg/build.ml
When trying to build `ppx_deriving` on windows (mingw, not cygwin), the build fails with the following error message:
```
Plugin tag "'package(cppo_ocamlbuild)'", line 1, characters 0-1:
Lexing error: Not a valid parametrized tag.
```
The reason is the build command defined in `pkg/build.ml`:
```ocaml
let ocamlbuild =
"ocamlbuild -use-ocamlfind -classic-display -plugin-tag 'package(cppo_ocamlbuild)'"
```
It is passed to `Sys.command` by `topkg`, and it is passed to `system`, which will use `cmd.exe` to execute it. Its behaviour with regards to quoting is very different from POSIX shells, and it will pass them to them to the program in a literal way.
Removing the simple quotes makes it work on mingw, but makes it fail on unix. I haven't found a way to quote it in a way that will please …
=> Fix build on windows (mingw)

src_plugins/ppx_deriving_ord.cppo.ml
The `[%ord: int]` expression expands to `Pervasives.compare`. Since this function is polymorphic, it may be used with other types. For example, the following expression typechecks:
```.ocaml
([%ord: int] : string -> string -> int)
```
This adds a type constraint on the `Pervasives.compare` call so that it becomes monomorphic. This is also more consistent with how this case is handled in the `eq` plugin.
Let me know what you think. Thanks!
=> Monomorphize compare function for builtin types

src/ppx_deriving.cppo.ml
This feature has two different implementations in the AST:
- in 4.02.3, it is an annotation on a type,
- in >= 4.03.0 it is straight in the constructor.
Note that this can break existing programs; however relying on `ppx_deriving` to do the right thing in that case seems dangerous.
Maybe an escape hatch could be added so that the recursive version is derived nonetheless.
It is an intermediate solution to #116. Solving it is tricky because it would be necessary to expose this to the plugins, breaking the API. It is probably easier to do so once 4.02.3 support is dropped, since the per-type semantics are difficult to handle.
Let me know what you think about these changes.
Thanks!
=> Raise an error when `type nonrec` is encountered

README.md, src_plugins/ppx_deriving_show.cppo.ml, src_test/test_deriving_show.cppo.ml
We were kind of bothered that `show` adds filename as prefix for all constructors. So we added very straightforward way to workaround this.  What was the expected way to hack this?
@eucpp
=> Show plugin: add option to skip module path

src/ppx_deriving.cppo.ml, src/ppx_deriving.mli
This PR adds a new function allowing one to declare a deriver that is interpret by another ppx rewriter:
```ocaml
(** [register_external name] registers [name] as an external deriver that is
not interpreted by ppx_deriving. Ppx_deriving will simply ignore [name]
when interpreting [[\@\@deriving]] annotations and leave it to be
expanded by another rewriter. *)
val register_external : string -> unit
```
The aim is to allow `ppx_deriver` and `ppx_type_conv` to live in harmony when linked as part of the same `ocaml-migrate-parsetree` driver once #123 is merged.
Currently `ppx_type_conv` does the following in order to interoperate with `ppx_deriving`:
- it exports its own derivers using the `Ppx_deriving` API
- it imports `ppx_deriving` derivers using …
=> Add Ppx_deriving.register_external

src_plugins/ppx_deriving_eq.cppo.ml, src_plugins/ppx_deriving_fold.cppo.ml, src_plugins/ppx_deriving_map.cppo.ml, src_plugins/ppx_deriving_ord.cppo.ml, src_plugins/ppx_deriving_show.cppo.ml, src_test/test_deriving_eq.cppo.ml, src_test/test_deriving_fold.cppo.ml, src_test/test_deriving_map.cppo.ml, src_test/test_deriving_ord.cppo.ml, src_test/test_deriving_show.cppo.ml
On OCaml 4.03.0+, this enables you to write
```ocaml
[%show: (string, string) result] (Ok "hello")
```
instead of being limited to:
```ocaml
[%show: (string, string) Result.result] (Ok "hello")
```
This should work for all standard plugins, not just "show".
=> Support result and not just Result.result

opam, src/ppx_deriving.cppo.ml
See #153: this is the start of an attempt to provide a 4.1 maintenance release that supports recent OCaml versions -- as a temporary solution to the current breakage for non-driverized users.
I started by creating a branch [4.1-maintenance](https://github.com/ocaml-ppx/ppx_deriving/commits/4.1-maintenance) on the upstream repo, which contains all the commits that went into 4.2 except for the omp-support changes in #141 -- currently it points exactly to 6b75b9e4804b253945ab61a76ed4af539d6caf90. A first point of potential discussion is whether we should indeed start from all those commits (some of there are small feature requests rather than bugfixes), but I think this is a reasonable basis to start from.
Then I just implemented 4.05-support using ugly preprocessor conditionals. This is the …
=> make ppx_deriving 4.1 build under 4.05

.travis.yml, CHANGELOG.md, src_plugins/ppx_deriving_enum.cppo.ml, src_plugins/ppx_deriving_eq.cppo.ml, src_plugins/ppx_deriving_fold.cppo.ml, src_plugins/ppx_deriving_iter.cppo.ml, src_plugins/ppx_deriving_map.cppo.ml, src_plugins/ppx_deriving_ord.cppo.ml, src_plugins/ppx_deriving_show.cppo.ml
This PR sits on top of #154. It adds support for 4.06.0 -- see also #153.
The changes in the drivers are very repetitive and annoying. It comes from the fact that the `label` field (morally) of the `Rtag` parsetree constructor gained a location, but the `label` fields of pattern and expression variant constructors is not located. If I had done this work earlier in the 4.06 release timeline, I would push for changing the parsetree to locate those labels as well -- this is clearly what the code tell us is the right approach for consumers. But I think this is too late for a fix in 4.06, so this will have to wait for 4.07 or never -- and the kludgy conditionals will remain, oh well.
=> 4.06 support

README.md
Previously there were broken links due to references to the orignal author, whitequark.
=> Change links in README to use ocaml-ppx org

.travis.yml, opam, src/ppx_deriving.cppo.ml, src/ppx_deriving.cppo.mli, src_plugins/ppx_deriving_enum.cppo.ml, src_plugins/ppx_deriving_eq.cppo.ml, src_plugins/ppx_deriving_fold.cppo.ml, src_plugins/ppx_deriving_iter.cppo.ml, src_plugins/ppx_deriving_map.cppo.ml, src_plugins/ppx_deriving_ord.cppo.ml, src_plugins/ppx_deriving_show.cppo.ml
This is a cherry-pick of @gasche changes from #155 to make the driverized version in the master branch work on OCaml 4.06.
This fixes ppx_deriving for jbuilder users when using ppx_deriving with other driverized ppxs. The error message was `Error: ppx_type_conv: 'show' is not a supported type type-conv generator`.
=> 4.06 support for ppx_deriving 4.2

src/ppx_deriving.cppo.ml, src/ppx_deriving.cppo.mli, src_plugins/ppx_deriving_fold.cppo.ml
Since 4.05.0, many base functions on type variables expect located
strings instead of raw strings. This is also the more informative
API -- locations can always be stripped out, but not regained.
I have mixed feelings about the choice of reusing the same function
names with a different API, which sort of enforces conditional
compilation on users as well. On the other hand, this choice was
designed to *reduce* the amount of conditional compilation required by
providing, for all OCaml versions, the right type for many client
usage patterns -- see
https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/64
=> free_vars_in_core_type and fold_{left,right}_type_decl now use `string loc`

src_plugins/ppx_deriving_eq.cppo.ml, src_plugins/ppx_deriving_ord.cppo.ml
Hi!
Adding these type annotations is necessary to prevent the following cases:
- : bool = true
and
- : int = 0
See #115 for a similar, solved, problem.
Thanks!
=> Restrict type for [%eq: unit] and [%ord: unit]

src_plugins/ppx_deriving_map.cppo.ml
Hi!
In some cases like the following, the generated code can emit instances of warning 41.
```ocaml
type 'a t1 = { x : 'a ; y1 : int } [@@deriving map]
type 'a t2 = { x : 'a ; y2 : int } [@@deriving map]
```
An alternative would be to add a constraint to the generated `map` function, but it does not seem to play well with polymorphism.
I also removed an intermediate `List.concat` since the list is always a singleton.
Let me know what you think.
Thanks!
=> map plugin: add a type annotation to avoid warning 41

CHANGELOG.md, src/ppx_deriving_runtime.mli, src_plugins/ppx_deriving_show.cppo.ml
Jane Street's Base emits a warning if Format is used without
the Caml. qualifier.
=> Use Caml.Format in show, to avoid warnings in Base

README.md
(from t -> bytes to t -> string)  and removed references to ppx_deriving_runtime.string from the Show section (replaced by string)
=> fixed misstyping of ppx_deriving.show 

src_plugins/ppx_deriving_show.cppo.ml
As reported in #171, using `[@@deriving show]` can trigger unwanted unused value warnings.
This PR adds a `[@@warning "-32"]` attribute to the generated `let show = ...` structure item to prevent such warnings.
I might look into a `[@@deriving pp]` alternate solution if I get some time to do so but this seemed like a simpler and faster first step.
This is my first PR on `ppx_deriving` so I might have gotten a few things wrong, especially around the `loc` to use for the generated code.
I tested this on our codebase at Cryptosense and it seems to do the job!
I guess it might be a good idea to expose a way to disable this feature since that makes it impossible for `pp` and `show` to trigger such a warning even when it would be relevant.
Let me know what you think!
=> Suppress warning 32 for show

.gitignore, src_test/map/test_deriving_map.cppo.ml
A couple ppx_deriving.map tests used `String.uppercase_ascii`. This was the only thing preventing the library from building and passing tests on 4.02.3; and it looked like, at their callsites, reliable behaviour w.r.t. higher-plane bytes wasn't important to the semantics of the test.
Let me know if there's a better solution!
=> 4.02 nit in the tests

src/api/ppx_deriving.cppo.ml
Fixes jaredly/reason-language-server#297
When using reason-language-server in a dune project, I started seeing the following error bubble up from the running language server instance when I introduced `ppx_deriving.std`:
```
Fatal error: exception (Invalid_argument Filename.chop_suffix)
Raised at file "parsing/ast_mapper.ml", line 826, characters 12-21
Called from file "parsing/ast_mapper.ml", line 843, characters 38-58
Called from file "parsing/ast_mapper.ml", line 878, characters 14-27
Called from file "src/driver.ml", line 1266, characters 6-39
Re-raised at file "parsing/location.ml", line 465, characters 14-25
Re-raised at file "parsing/location.ml", line 465, characters 14-25
Re-raised at file "parsing/location.ml", line 465, characters 14-25
Re-raised at file "parsing/location.ml", …
```
=> Support empty Location.input_name in input ast

src/runtime/ppx_deriving_runtime.cppo.mli
The comment in the `.ml` file mentions this is done for backwards compatibility but it wasn't actually exposed in the interface.
=> Add `Result.result` to the .mli file

src_plugins/eq/ppx_deriving_eq.cppo.ml, src_plugins/fold/ppx_deriving_fold.cppo.ml, src_plugins/iter/ppx_deriving_iter.cppo.ml, src_plugins/map/ppx_deriving_map.cppo.ml, src_plugins/ord/ppx_deriving_ord.cppo.ml, src_plugins/show/ppx_deriving_show.cppo.ml, src_test/show/test_deriving_show.cppo.ml
fixes #194
This bug is likely to also affect out-of-tree plugins, which should
probably be notified -- attribute propagation is currently not
centralized and has to be done by each plugin.
=> Fix handling of attributes of record fields in inline records

src/runtime/ppx_deriving_runtime.cppo.ml, src/runtime/ppx_deriving_runtime.cppo.mli
cc #197 @anmonteiro . Would that change avoid any Result-related code change in 
https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/99 ?
My goal is not only to fix ppx_deriving_yojson or make our life easier, but to ensure that we limit breaking other plugins as much as possible. For that reason, even the partial workaround that you used in https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/99/commits/3e16cd22d6c410c7d5362ed68334edda742094e9 is not fully satisfying.
=> Result: ensure Result.t and Result.result are exposed under both 4.08 and earlier versions

src/api/ppx_deriving.cppo.ml, src_test/api/dune, src_test/api/test_api.cppo.ml
The variables listed in free_vars_in_core_type should occur in lexical
order of appearance, left-to-right: for example with `('b * 'a)
option`, we want to see `'b` before `'a`, so the resulting list is [b; a].
There was a bug in the ordering in the case where a variable is
repeated (`('b * 'a) option * 'b`); in that case it would use for
a variable the ordering of the rightmost occurrence, instead of the
leftmost occurrence, to determine placement. It would thus return [a;
b], while we expect [b; a] in this case -- this is what is returned
with this patch.
=> fix an ordering bug in free_vars_in_core_type

src_test/show/test_deriving_show.cppo.ml
Fixing #199 on 4.02.3. Somebody should sanity-check this; it was just the simplest way for me to get the tests passing. (hi! 🙋‍♀️ yep, that's me, still over here being an annoyance 🤣)
Presumably, whatever feature he's adding support for is unavailable on the 4.02-series? Nonetheless, being present in the tests-file at all breaks them on 4.02.3 for me:
```
ocamlopt .ppx/20e3ffc6dc013e448ad889e12acbb4d5/ppx.exe
ppx src_test/map/test_deriving_map.pp.ml
ocamlopt src_test/deriving/test_ppx_deriving.exe
ocamldep src_test/map/.test_deriving_map.eobjs/test_deriving_map.pp.ml.d
ocamlopt .ppx/4c4b0dc849c26ef889ee6f55cb3a0672/ppx.exe
ocamlc src_test/map/.test_deriving_map.eobjs/byte/test_deriving_map.{cmi,cmo,cmt}
ppx src_test/show/test_deriving_show.pp.ml (exit 1)
(cd _build/default && …
```
=> Gate inline-records-with-attributes test to >=4.03

.travis.yml
We require >=4.02.2, but in fact OCAML_VERSION=4.02 automatically
picks 4.02.3 nowadays, so CI on 4.02 should work correctly.
(CI testing for this PR should break now and work once #204 is merged.)
=> add back 4.02 CI

README.md
Dune is now the community's de facto standard build system, and seems to [automatically support linking drivers into a single executable](https://readthedocs.org/projects/dune/downloads/pdf/latest/#subsection.5.7.2), which seems like a big enough deal to warrant its own paragraph in the readme.
=> document Dune usage

src/ppx_deriving_main.cppo.ml
This fixes the segmentation fault reported by kit-ty-kate:
https://github.com/ocaml-ppx/ppx_deriving/pull/210#issuecomment-632136159
I don't know where this segmentation fault precisely occurred, but I suppose that converting the mapper makes Migrate_parsetree make a lot of conversion between each sub-tree of the AST. The new approach is a bit more verbose but conceptually simpler and should be more efficient.
=> Only convert needed parts of the AST instead of converting mapper

src/runtime/ppx_deriving_runtime.cppo.ml, src/runtime/ppx_deriving_runtime.cppo.mli
Some equalities were missing in `Ppx_deriving_runtime`, for instance the equality between `Pervasives.result` and `Result.result`, which leads to some strange type errors (for instance, the one corrected here for OCaml <4.08: https://github.com/ocaml-ppx/ppx_deriving/pull/222/commits/f89e120c8f8fc1cd1e319bf3e8217d8e7e62a923).
Instead of trying to enumerate all equalities explicitly, this PR proposes to use the construction
```ocaml
include module type of struct
include M
end
```
to precisely get the signature of `include M`.
Moreover, it seems that we do not lose anything by using module aliases in signatures.
=> Use "include module type of struct include" to get all equalities

src/api/ppx_deriving.cppo.ml, src/api/ppx_deriving.cppo.mli, src/runtime/ppx_deriving_runtime.cppo.ml, src/runtime/ppx_deriving_runtime.cppo.mli
This pull-request cherry-picks into `master` the following changes introduced in the `pre-ppxlib` branch:
- the `Option` compatibility module in `Ppx_deriving_runtime`,
- the `string_of_{expression,constant}_opt` functions in `Ppx_deriving`.
=> Cherry picking some pre-ppxlib changes into master

src/runtime/ppx_deriving_runtime.cppo.ml, src/runtime/ppx_deriving_runtime.cppo.mli
This pull-request cherry-picks https://github.com/ocaml-ppx/ppx_deriving/pull/223 into `pre-ppxlib`.
=> Cherry-picking stronger type equalities into pre-ppxlib

ppx_deriving.opam
This PR:
* Uses `{dev}` instead of `{pinned}` for the `dune subst` command (see https://github.com/ocaml/dune/pull/3647)
* Removes mentions of unsupported versions of OCaml
* Restrict the `ppxlib` dependency to `< 0.14.0`. Currently fails with this error with `ppxlib.0.14.0`:
```
#=== ERROR while compiling ppx_deriving.dev ===================================#
```
=> Fix and improve the opam file

ppx_deriving.opam, src/api/ppx_deriving.cppo.ml, src/ppx_deriving_main.cppo.ml
I just released ppx_deriving 5.0. Currently it only supports ppxlib up to 0.13.0. This PR increase the support to 0.15.0.
Once that's done I'll do another release: ppx_deriving 5.1
After that, https://github.com/ocaml-ppx/ppx_deriving/pull/231 will be required to upgrade to ppxlib 0.16.0
=> Upgrade to ppxlib 0.15.0

.travis.yml
Gabriel Scherer reported that ppx_deriving_protocol does not depend on ppx_deriving.
https://github.com/ocaml-ppx/ppx_deriving/pull/227#issuecomment-633576290
=> Remove ppx_deriving_protocol from REVDEPS

ppx_deriving.opam, src/api/dune, src/dune, src_test/api/dune, src_test/create/dune, src_test/deriving/dune, src_test/enum/dune, src_test/eq/dune, src_test/fold/dune, src_test/iter/dune, src_test/make/dune, src_test/map/dune, src_test/ord/dune, src_test/runtime/dune, src_test/show/dune
This PR cherry-picks a few commits from https://github.com/ocaml-ppx/ppx_deriving/pull/240 as it is a bit harder than first thought to get rid of the dependency on `result`.
I'll do one last release after this.
=> Remove unused dependencies and upgrade to ounit2

dune, src/api/ppx_deriving.cppo.ml, src_plugins/create/ppx_deriving_create.cppo.ml, src_plugins/enum/ppx_deriving_enum.cppo.ml, src_plugins/eq/ppx_deriving_eq.cppo.ml, src_plugins/fold/ppx_deriving_fold.cppo.ml, src_plugins/iter/ppx_deriving_iter.cppo.ml, src_plugins/make/ppx_deriving_make.cppo.ml, src_plugins/map/ppx_deriving_map.cppo.ml, src_plugins/ord/ppx_deriving_ord.cppo.ml, src_plugins/show/ppx_deriving_show.cppo.ml, src_test/api/test_api.cppo.ml, src_test/map/test_deriving_map.cppo.ml, src_test/show/test_deriving_show.cppo.ml
=> (almost) use the set of standard flags from dune

src/api/ppx_deriving.cppo.ml
This is an attempt at fixing the last issue of ppx_deriving with ocaml-migrate-parsetree 2.0
The problem was that making ppx_deriving a "preprocesor type ppxlib extension", made it imcompatible with other "preprocessor type ppxlib extensions" such as `optcomp` and triggered errors in a handful of packages in opam-repository.
From what I understand this was done to enforce an order between ppxs, and when mentioning this issue the ppxlib devs told me to use the `Ppxlib.Deriving` API. However, I'm no expert in either `ppxlib` nor `ppx_deriving` and didn't manage to make it work in a reasonable time.
Here I'm using the cheap method of simply stop caring about orders, I've ran a test on every opam packages for OCaml 4.11 with this change and no issue was found. So, to me, this seems safe to do …
=> Make ppx deriving compatible with preprocessor type ppxlib extensions

src/api/ppx_deriving.cppo.ml
This is required for `ppx_deriving_protobuf` to work with minimal changes. See: https://github.com/ocaml-ppx/ppx_deriving_protobuf/pull/39
=> Fix some of Ast_convenience's functions when giving a full path ident (e.g. M.ident, not just ident)

src/api/ppx_deriving.cppo.ml, src_plugins/eq/ppx_deriving_eq.cppo.ml, src_plugins/ord/ppx_deriving_ord.cppo.ml, src_test/eq/test_deriving_eq.cppo.ml, src_test/ord/test_deriving_ord.cppo.ml
After switching a large project from manual `equal` and `compare` implementations to ones derived by ppx_deriving (https://github.com/goblint/analyzer/pull/227), we noticed significant performance decreases in in those functions (https://github.com/goblint/analyzer/issues/265).
Benchmarking the generated `equal` functions directly (https://github.com/goblint/analyzer/blob/a21f33511183074c693c15269990210b283ae045/bench/deriving/benchEq.ml, executable independently from our project) showed up to **3 times** slowdown. For example, when the old manual implementation
```ocaml
let equal (x1, y1) (x2, y2) = Int.equal x1 x2 && String.equal y1 y2
```
was replaced with one derived for `Int.t * String.t`.
The modules `Int` and `String` are just chosen as example, we often use functors where the …
=> Optimize forwarding in eq and ord plugins

dune
compat_macros.cppo doesn't exist
@kit-ty-kate there's no bug, but it's confusing to keep this
=> chore: remove artifact

ppx_deriving.opam
In #263 I noticed the experimental lower-bounds job in opam-ci failing with
```
/home/opam/.opam/4.05/bin/cppo: unknown option '-V'.
```
This adds the corresponding cppo lower bound.
=> Add missing cppo 1.1.0 lower bound

CHANGELOG.md, ppx_deriving.opam, src/api/ppx_deriving.cppo.ml, src/api/ppx_deriving.cppo.mli, src_plugins/create/ppx_deriving_create.cppo.ml, src_plugins/enum/ppx_deriving_enum.cppo.ml, src_plugins/eq/ppx_deriving_eq.cppo.ml, src_plugins/fold/ppx_deriving_fold.cppo.ml, src_plugins/iter/ppx_deriving_iter.cppo.ml, src_plugins/make/ppx_deriving_make.cppo.ml, src_plugins/map/ppx_deriving_map.cppo.ml, src_plugins/ord/ppx_deriving_ord.cppo.ml, src_plugins/show/ppx_deriving_show.cppo.ml, src_test/deriving/test_ppx_deriving.ml
This realizes part of #250:
1. All the standard deriving plugins defined here are switched to register themselves directly with ppxlib and declare their attributes directly with ppxlib.
2. ~~Deprecates only parts of ppx_deriving API, namely ppx_deriving deriver registration and attribute support. All the other utility functions remain undeprecated since many are still missing from ppxlib (https://github.com/ocaml-ppx/ppxlib/issues/317).~~
3. Delegates ppx_deriving quoter to ppxlib quoter.
Notably, this makes `[@@deriving_inline ...]` work on these standard derivers.
=> Port standard plugins to ppxlib registration and attributes

CHANGELOG.md
Since #263 is finally merged and #252 is also unreleased, it would be great to have a new release over 3 years. I suppose version 5.3 would make sense. Although #263 is a big internal change, it shouldn't be breaking (hopefully), but we'll see from opam-repository CI.
An eventual version 6.0 could be the actual deprecation of ppx_deriving API (#250), but there are still things to move over (https://github.com/ocaml-ppx/ppxlib/issues/317).
This PR is just an update of the unreleased CHANGELOG.
=> Add missing unreleased CHANGELOG entries

src_plugins/show/ppx_deriving_show.ml
Even though the argument is unused in `.mli` files as it only affects the implementation and not the signature of the function, it used to be accepted back when declared via `ppx_deriving.api` so we need to keep it that way for compatibility.
=> Declare `show`'s `with_path` argument for interface deriver as well

src_plugins/fold/ppx_deriving_fold.ml, src_plugins/iter/ppx_deriving_iter.ml, src_plugins/map/ppx_deriving_map.ml
These don't seem very useful:
1. On types without free variables, they're just identity.
2. On types with free variables, they require specially-named `poly_` functions present in the scope. These are usually declared at the type declaration level of the deriver.
These also appear to be unused according to sherlocode (we'll see about opam-repository CI...).
Removing map avoids a superficial conflict with ppx_let: https://github.com/janestreet/ppx_let/issues/14.
Of course, the morally right thing would be to declare a conflict with ppx_let for now and remove the conflict once ppx_let prefixes their extension. However, that would likely be inconvenient for many and for practical backwards-compatibility it's easier to remove something which doesn't seem to be used.
=> Remove extensions from fold, iter and map plugins

ppx_deriving.opam, src/api/dune, src/api/ppx_deriving.cppo.ml, src/api/ppx_deriving.cppo.mli, src/runtime/dune, src/runtime/ppx_deriving_runtime.cppo.ml, src/runtime/ppx_deriving_runtime.cppo.mli, src_plugins/eq/ppx_deriving_eq.ml, src_plugins/fold/ppx_deriving_fold.ml, src_plugins/iter/ppx_deriving_iter.ml, src_plugins/map/ppx_deriving_map.ml, src_plugins/ord/ppx_deriving_ord.ml, src_plugins/show/ppx_deriving_show.ml, src_test/eq/test_deriving_eq.cppo.ml, src_test/fold/test_deriving_fold.cppo.ml, src_test/iter/test_deriving_iter.cppo.ml, src_test/map/test_deriving_map.cppo.ml, src_test/ord/test_deriving_ord.cppo.ml, src_test/runtime/test_runtime.cppo.ml, src_test/show/test_deriving_show.cppo.ml
- even though the `Result` module was only added in OCaml 4.08:
- the type `{Pervasives,Stdlib}.result` has been added as far back as OCaml 4.03 
- ppx_deriving's lower bound is OCaml 4.05, so it should be fine to remove this dependency
=> drop the `result` compatibility package dependency

CHANGELOG.md, README.md, src_plugins/make/ppx_deriving_make.ml, src_test/make/test_deriving_make.ml
Fixes #272.
There was a bug with `[@@deriving make]` that caused errors if it was used on a set of type declarations, recursive or non recursive, that contained a non record type.
The deriver was applied to all type declarations in the set, regardless of where the attributes was attached and failed on the ones that weren't record types.
There is no particularly nice way to handle this in ppxlib, I assume the design decision was that one would only attach a single `[@@deriving ...]` attribute per set and the individual derivers would be responsible to decide which type declarations are relevant.
The driver does allow attaching multiple `[@@deriving ...]` attributes in the same set but performs a merge of all of them so it can lead to confusing situations for the end user.
With all that in …
=> Fix a bug with [@@deriving make] on type declarations sets

CHANGELOG.md, src/runtime/ppx_deriving_runtime.cppo.ml, src/runtime/ppx_deriving_runtime.cppo.mli
When removing our unneeded dependency on the `result` compat package, we inadvertently remove the `Result` module in `Ppx_deriving_runtime` which broke its API.
This should fix the issue we ran into when attempting to [release 6.0.0](https://github.com/ocaml/opam-repository/pull/25675#issuecomment-2057097995).
=> Reintroduce a Ppx_deriving_runtime Result module for compat

CHANGELOG.md, src_plugins/make/ppx_deriving_make.ml, src_test/make/test_deriving_make.ml
I introduced a bug in `ppx_deriving.make` when working on #281 and inadvertently changed the ordering of the arguments of the generated function.
The test suite failed to pick it up because the signature was also generated with `[@@deriving make]` and the ordering was swapped in both the signature and structure derivers.
I added a module with a handwritten signature and a derived implementation so that this can't happen again in the future.
=> Fix the ordering of `make`'s arguments
